// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PracticaFinal.Data;

#nullable disable

namespace PracticaFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207005237_FixPrecioPrecision")]
    partial class FixPrecioPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PracticaFinal.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DT")
                        .HasColumnType("bigint");

                    b.Property<long>("Document")
                        .HasColumnType("bigint");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservationsId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("Whatsapp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReservationsId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PracticaFinal.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdService");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("PracticaFinal.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReservationsId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReservationsId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("PracticaFinal.Models.Cliente", b =>
                {
                    b.HasOne("PracticaFinal.Models.Reservation", "Reservations")
                        .WithMany()
                        .HasForeignKey("ReservationsId");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("PracticaFinal.Models.Reservation", b =>
                {
                    b.HasOne("PracticaFinal.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PracticaFinal.Models.Servicio", "Servico")
                        .WithMany()
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("PracticaFinal.Models.Servicio", b =>
                {
                    b.HasOne("PracticaFinal.Models.Reservation", "Reservations")
                        .WithMany()
                        .HasForeignKey("ReservationsId");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
